### ISSUE TITLE
Aluminum (with SE) - Productivity

### ISSUE THREAD

**Issue by Xynariz** [brevven/bz#29]
Is it intended for this alumina recipe to not be able to take productivity?  (Same question for the non-vulcanite recipe)
![image](https://user-images.githubusercontent.com/8754737/187019124-aa3e3131-0781-4558-9353-a0d51a71515b.png)
![image](https://user-images.githubusercontent.com/8754737/187019129-70e799e9-e75f-4b6e-b879-ad53be4cbe1c.png)

([Source: Xynariz](https://discord.com/channels/935068537075167263/935068537775595622/939428932850188288))

**Comment by brevven** [comment]
Thank you! Fixed in 0.1.4
